### ISSUE TITLE
error: ‘TH_INDEX_BASE’ undeclared

### ISSUE THREAD

**Issue by hellf** [xhzhao/Optimized-Torch#2]
Hi I have some problem doing 'luarocks installl nn' after installing this torch.
1) OS: ubuntu 14.04, cuda:7.5,  cudnn:5.1.3
2) MKL:installed in /opt/intel
3) path setting:

    nano .bashrc
    PATH=/usr/local/cuda/bin:$PATH
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
    export CUDA_HOME=/usr/local/cuda
    export PATH=/home/user/torch/install/bin:$PATH
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/user/nccl/lib
    . /home/user/torch/install/bin/torch-activate
    . /opt/intel/bin/compilervars.sh intel64
    export CMAKE_INCLUDE_PATH=$CMAKE_INCLUDE_PATH:/opt/intel/compilers_and_libraries/linux/include:/opt/intel/mkl/include
    export CMAKE_LIBRARY_PATH=$CMAKE_LIBRARY_PATH:/opt/intel/compilers_and_libraries/linux/lib/intel64:/opt/intel/mkl/lib/intel64
    . /home/user/torch/install/bin/torch-activate

4) Install sequence

    curl -sk https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash -e
    git clone https://github.com/xhzhao/distro.git ./torch --recursive
    bash install-deps
    ./install.sh
    luarocks install nn

5) error message

    user@user-250:~/torch$ luarocks install nn
    Installing https://raw.githubusercontent.com/torch/rocks/master/nn-scm-1.rockspec...
    Using https://raw.githubusercontent.com/torch/rocks/master/nn-scm-1.rockspec... switching to 'build' mode
    Cloning into 'nn'...
    remote: Counting objects: 281, done.
    remote: Compressing objects: 100% (239/239), done.
    remote: Total 281 (delta 67), reused 123 (delta 40), pack-reused 0
    Receiving objects: 100% (281/281), 606.26 KiB | 1.08 MiB/s, done.
    Resolving deltas: 100% (67/67), done.
    Checking connectivity... done.
    cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/user/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/user/torch/install/lib/luarocks/rocks/nn/scm-1" && make

    -- The C compiler identification is GNU 4.8.4
    -- The CXX compiler identification is GNU 4.8.4
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Found Torch7 in /home/user/torch/install
    -- Try OpenMP C flag = [-fopenmp]
    -- Performing Test OpenMP_FLAG_DETECTED
    -- Performing Test OpenMP_FLAG_DETECTED - Success
    -- Try OpenMP CXX flag = [-fopenmp]
    -- Performing Test OpenMP_FLAG_DETECTED
    -- Performing Test OpenMP_FLAG_DETECTED - Success
    -- Found OpenMP: -fopenmp
    -- Compiling with OpenMP support
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/luarocks_nn-scm-1-607/nn/build
    Scanning dependencies of target THNN
    [100%] Building C object lib/THNN/CMakeFiles/THNN.dir/init.c.o
    In file included from generic/ClassNLLCriterion.c:1:0,
                     from /tmp/luarocks_nn-scm-1-607/nn/lib/THNN/init.c:14:
    /tmp/luarocks_nn-scm-1-607/nn/lib/THNN/generic/ClassNLLCriterion.c: In function ‘THNN_FloatClassNLLCriterion_updateOutput’:
    /tmp/luarocks_nn-scm-1-607/nn/lib/THNN/generic/ClassNLLCriterion.c:40:39: error: ‘TH_INDEX_BASE’ undeclared (first use in this function)
         int cur_target = target_data[0] - TH_INDEX_BASE;
                                           ^
    /tmp/luarocks_nn-scm-1-607/nn/lib/THNN/generic/ClassNLLCriterion.c:40:39: note: each undeclared identifier is reported only once for each function it appears in
    /tmp/luarocks_nn-scm-1-607/nn/lib/THNN/generic/ClassNLLCriterion.c: In function ‘THNN_FloatClassNLLCriterion_updateGradInput’:
    /tmp/luarocks_nn-scm-1-607/nn/lib/THNN/generic/ClassNLLCriterion.c:114:39: error: ‘TH_INDEX_BASE’ undeclared (first use in this function)
         int cur_target = target_data[0] - TH_INDEX_BASE;

What should I do? 
I have reinstalled after cleaning with these commands.

    luarocks remove torch --force
    cd torch
    ./clean.sh
    curl -s https://raw.githubusercontent.com/torch/ezinstall/master/clean-old.sh | bash
    rm -rf torch/

**Comment by xhzhao** [comment]
hi hellf, if you run"./install.sh", then the nn module is already installed to you torch, so you don't need to run "luarocks install nn" again.

**Comment by hellf** [comment]
Oh Thank you. That will be help :)
